### ISSUE TITLE
can i use this to setup my manga website 

### ISSUE THREAD

**Issue by mymangawebsite** [fake-name/MangaCMS#10]
can i use this to scarpe content from manga fox or siliar sites and automatically add it to my website without doing it manually if i can how

**Comment by fake-name** [comment]
It should be possible. You could attach to the download process function and add a hook that uploads the fetched manga to whatever CMS "your website" uses (there's already a upload plugin for Madokami).

With regard to "how", you'd really need to know (or at least be willing to lean) python to do it. Maybe see if you can get the base system working first (it's not too trivial, follow the readme).

At minimum, you need to be comfortable with linux to get anywhere.
