### ISSUE TITLE
[Feature request] Change database / docker

### ISSUE THREAD

**Issue by duongphuhiep** [fake-name/MangaCMS#11]
Hello,

The project seems awesome.. however at the first glance, it required to install PostgreSQL.

My PC was bloated with so many database (couchbase, thinkdb, mysql..) which occupied all the port of my localhost.. I've just clean them up and don't want to bloat my PC again.

I suggest that 

1) you could replace PostgreSql to a more lightweight / unobustrive database - some embedded database which required no setup such as SqlLite, Firebird, H2...

2) or make a [Docker image](https://www.docker.com/), so that everyone could run the web server with a single-line of command (on Windows, Linux) without the need to install Python / PostgrSql

Anyway, they were just suggestion at the first glance and because I couldn't install PostgreSQL for now.

Please keep up the good job.

Thanks

**Comment by fake-name** [comment]
1. The project started with SQLite, and quickly outgrew it. Index warming on pageload after a period if time idle was resulting in multi-second page rendering times.  
At this point, the DB layer is heavily, **heavily** hard-coded to depend on PsycoPG2, and changing it would be a massive undertaking. Furthermore, a number of the data-structure and search mechanisms are postgresql-specific. Also, PostgreSQL is better anyways (/opinion).

2. That's not a terrible idea, but it probably won't happen in the near future. The last time I used docker, it *still* didn't have a good way to provision VMs with per-vm configuration, and ease-of-instability isn't really a major target anyways. The web server is kind of useless without the scraper, and the scraper needs to run continuously, so the whole "spin up a new instance on demand" architecture is somewhat opposed to the way the scraper works, so it's a rather pointless exercise anyways.
