### ISSUE TITLE
Ubuntu Xenial Installation

### ISSUE THREAD

**Issue by typhoe** [fake-name/MangaCMS#12]
Hi,

I'm trying to set up MangaCMS on a ubuntu Xenial (16.04 LTS) server.

So I follow README.md:

# Get MangaCMS
`cd /opt`
`git clone https://github.com/fake-name/MangaCMS.git`

# Correct script installDeps.sh for xenial 
(Postgresql 9.5 already available in xenial, but python and libtiff versions changed)
`sed -i 's,python3.4,python3.5,g' /opt/MangaCMS/setuptools/installDeps.sh`
`sed -i 's,libtiff4-dev,libtiff5-dev,g' /opt/MangaCMS/setuptools/installDeps.sh`

# Install deps
`chmod +x /opt/MangaCMS/setuptools/installDeps.sh`
`/opt/MangaCMS/setuptools/installDeps.sh`

# Config PostgreSQL
`grep mangacms /etc/postgresql/9.5/main/pg_hba.conf || echo "local mangacms all md5" >> /etc/postgresql/9.5/main/pg_hba.conf`
`echo "CREATE USER mangacmsuser;" | sudo -u postgres psql postgres`
`echo "\password mangacmsuser" | sudo -u postgres psql postgres`
`echo "CREATE DATABASE mangacms;" | sudo -u postgres psql postgres`
`echo "GRANT ALL PRIVILEGES ON DATABASE mangacms to mangacmsuser;" | sudo -u postgres psql postgres`
`echo "CREATE EXTENSION citext;" | sudo -u postgres psql postgres`
(that tells me ERROR:  extension "citext" already exists, I assume it's ok. citext seems to have been installed from installDeps.sh)

# Launch firstRun.py
`cd /opt/MangaCMS/ && python3 /opt/MangaCMS/firstRun.py`
And there I get this error:

_DB Not setup for munamelist.
DB Not setup for munamelist.
DB Not setup for mangaseries.
DB Not setup for mangaseries.
Database connection pool init!
<class 'ScrapePlugins.BuMonitor.MonitorRun.BuWatchMonitor'>
Traceback (most recent call last):
  File "/opt/MangaCMS/firstRun.py", line 37, in <module>
    firstRun()
  File "/opt/MangaCMS/firstRun.py", line 33, in firstRun
    tmp = plg()
  File "/opt/MangaCMS/ScrapePlugins/MonitorDbBase.py", line 60, in \_\_init\_\_
    self.checkInitPrimaryDb()
  File "/opt/MangaCMS/ScrapePlugins/MonitorDbBase.py", line 544, in checkInitPrimaryDb
    );''' % self.tableName)
psycopg2.ProgrammingError: type "citext" does not exist
LINE 4:             buName          CITEXT,
                                    ^_

Can you help me to see what I missed?
Thank you

**Comment by fake-name** [comment]
I think the `CITEXT` extension is being bootstrapped into the wrong database. 

Can you see if the pushed changes fix the issue? Alternatively, execute `sudo -u postgres psql -c 'CREATE EXTENSION IF NOT EXISTS citext SCHEMA pg_catalog;;'` from a terminal.

I think this should install `CITEXT` globally (see http://stackoverflow.com/questions/12986368/installing-postgresql-extension-to-all-schemas).

**Comment by fake-name** [comment]
If that doesn't fix it, you should be able to fix it by starting `psql` (`sudo -u postgres psql`), changing to the database you created (it's the setting `DATABASE_DB_NAME` in settings.py -> `\c <DATABASE_DB_NAME>` in the `psql` prompt), and manually installing the extension (`CREATE EXTENSION citext;`). 

I'm not sure what state the DB you have is in, but you shouldn't be able to break anything in any event (creating a installed extension just results in an error).

**Comment by typhoe** [comment]
Hi, and thank you for your quick answer.

I did:
`git stash`
`git pull`
# Correct again script installdeps for xenial
`sed -i 's,python3.4,python3.5,g' /opt/MangaCMS/setuptools/installDeps.sh`
`sed -i 's,libtiff4-dev,libtiff5-dev,g' /opt/MangaCMS/setuptools/installDeps.sh`
# Install deps again
`chmod +x /opt/MangaCMS/setuptools/installDeps.sh`
`/opt/MangaCMS/setuptools/installDeps.sh`

`cd /opt/MangaCMS/ && python3 /opt/MangaCMS/firstRun.py`
DB Not setup for munamelist.
DB Not setup for munamelist.
DB Not setup for mangaseries.
DB Not setup for mangaseries.
Database connection pool init!
<class 'ScrapePlugins.BuMonitor.MonitorRun.BuWatchMonitor'>
Traceback (most recent call last):
  File "/opt/MangaCMS/firstRun.py", line 37, in <module>
    firstRun()
  File "/opt/MangaCMS/firstRun.py", line 33, in firstRun
    tmp = plg()
  File "/opt/MangaCMS/ScrapePlugins/MonitorDbBase.py", line 60, in __init__
    self.checkInitPrimaryDb()
  File "/opt/MangaCMS/ScrapePlugins/MonitorDbBase.py", line 544, in checkInitPrimaryDb
    );''' % self.tableName)
psycopg2.ProgrammingError: type "citext" does not exist
LINE 4:             buName          CITEXT,
                                    ^
So, same error so far...

Tried:
sudo -u postgres psql -c 'CREATE EXTENSION IF NOT EXISTS citext SCHEMA pg_catalog;;'
NOTICE:  extension "citext" already exists, skipping
CREATE EXTENSION

But again, same error with firstRun.py

Then, your last suggestion:
`sudo -u postgres psql`
`postgres=# \c mangacms`
You are now connected to database "mangacms" as user "postgres".
`mangacms=# CREATE EXTENSION citext;`
CREATE EXTENSION

And it seems far better:
`cd /opt/MangaCMS/ && python3 /opt/MangaCMS/firstRun.py`
DB Not setup for munamelist.
DB Not setup for munamelist.
DB Not setup for mangaseries.
DB Not setup for mangaseries.
Database connection pool init!
<class 'ScrapePlugins.BuMonitor.MonitorRun.BuWatchMonitor'>
muReleases_nameTable_buId_index muReleases CREATE INDEX %s ON %s (buId      )
<class 'ScrapePlugins.BuMonitor.ChangeMonitor.BuDateUpdater'>
<class 'ScrapePlugins.DjMoeLoader.djMoeDbLoader.DjMoeDbLoader'>
<class 'ScrapePlugins.BtSeriesFetcher.btSeriesEnqueuer.BtSeriesEnqueuer'>
<class 'ScrapePlugins.BtLoader.btFeedLoader.BtFeedLoader'>

And now, I can run mainScrape.py

And well... it seems to scrape and DOWNLOAD everything??? I already have 3.6Go of files downloaded.
I though I had to select what to scrape from the web interface... Is it directly in settings.py ?

An other problem I have is that the web interface doesn't work.
I can launch the process:
`python3 mainWeb.py` 
Tables =  ['logtable', 'apscheduler_jobs', 'schemarev', 'pluginstatus', 'munamelist', 'mangaseries', 'mureleases', 'hentaiitems', 'mangaitems', 'batotoseries', 'mangaitemcounts']
Database Schema Up to date
Setting up loggers....
done
<...>
Database connection pool init!
<...>
[11/Jan/2017:17:50:51] ENGINE Serving on http://0.0.0.0:8081
[11/Jan/2017:17:50:51] ENGINE Bus STARTED
Main.NSLookup - INFO - Refresh call complete. Have 278 keys

So, it seems ok.

But when I try to connect from a browser, I get a HTTP 500:
Main.SessionMgr - INFO - Checking if any of 0 session cookies need to be pruned due to age
Main.SessionMgr - INFO - Creating session
Main.WebSrv - INFO - Starting Serving old-style request from 192.168.1.204
Main.WebSrv - INFO - Appending 'index.mako'
Content path =  /srv/MangaCMS/ctnt/staticContent/index.mako False
Raw content request! /srv/MangaCMS/ctnt/staticContent/index.mako /srv/MangaCMS/ctnt/staticContent
Main.WebSrv - INFO - Request for raw content at URL /srv/MangaCMS/ctnt/staticContent/index.mako
Main.WebSrv - ERROR - Page rendering error! url: /srv/MangaCMS/ctnt/staticContent/index.mako
Main.WebSrv - ERROR - Traceback (most recent call last):
  File "/opt/MangaCMS/wsgi_server.py", line 331, in getPageHaveAuth
    return self.getRawContent(reqPath, self.static_directory)
  File "/opt/MangaCMS/wsgi_server.py", line 202, in getRawContent
    with open(reqPath, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/srv/MangaCMS/ctnt/staticContent/index.mako'

[11/Jan/2017:17:54:19] ENGINE TopLevelLookupException("Cant locate template for uri 'error.mako'",)
Traceback (most recent call last):
  File "/opt/MangaCMS/wsgi_server.py", line 331, in getPageHaveAuth
    return self.getRawContent(reqPath, self.static_directory)
  File "/opt/MangaCMS/wsgi_server.py", line 202, in getRawContent
    with open(reqPath, "rb") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/srv/MangaCMS/ctnt/staticContent/index.mako'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/mako/lookup.py", line 247, in get_template
    return self._check(uri, self._collection[uri])
KeyError: 'error.mako'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/wsgiserver/__init__.py", line 1408, in communicate
    req.respond()
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/wsgiserver/__init__.py", line 862, in respond
    self.server.gateway(self).respond()
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/wsgiserver/__init__.py", line 2335, in respond
    response = self.req.server.wsgi_app(self.env, self.start_response)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cptree.py", line 287, in __call__
    return app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 236, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 211, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/usr/local/lib/python3.5/dist-packages/pyramid/compat.py", line 148, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/router.py", line 158, in handle_request
    view_name
  File "/usr/local/lib/python3.5/dist-packages/pyramid/view.py", line 547, in _call_view
    response = view_callable(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 257, in wrapper
    response = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 413, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 106, in mapped_view
    return _mapped_view(context, request)
  File "/usr/local/lib/python3.5/dist-packages/pyramid/viewderivers.py", line 147, in _requestonly_view
    response = view(request)
  File "/opt/MangaCMS/wsgi_server.py", line 214, in getPage
    return self.getPageHaveAuth(request, context=self.old_directory, engine=self.lookupEngine_base)
  File "/opt/MangaCMS/wsgi_server.py", line 341, in getPageHaveAuth
    pgTemplate = engine.get_template("error.mako")
  File "/usr/local/lib/python3.5/dist-packages/mako/lookup.py", line 261, in get_template
    "Cant locate template for uri %r" % uri)
mako.exceptions.TopLevelLookupException: Cant locate template for uri 'error.mako'

Any idea why?
The directory is empty:
root@manga:/opt/MangaCMS# ls -lh /srv/MangaCMS/ctnt/staticContent/
total 0

**Comment by fake-name** [comment]
That.... is very strange. [staticContent](https://github.com/fake-name/MangaCMS/tree/master/ctnt/staticContent) definitely has contents in the repository. I'm not sure what's going on. Something weird with your checkout

------

> And well... it seems to scrape and DOWNLOAD everything??? I already have 3.6Go of files downloaded.
> I though I had to select what to scrape from the web interface... Is it directly in settings.py ?

[From the readme](https://github.com/fake-name/MangaCMS/blob/master/README.md):


> This is a "firehose-style" scraper, in that it doesn't really provide any built in facilities for filtering the scraped content. It basically just scrapes everything, all the time. This is because my own interests are more along the lines of archiving everything, rather then just selective downloading (there are other tools for that).

**Comment by fake-name** [comment]
Did that clear up your issues?

**Comment by typhoe** [comment]
Hi,

I didn't have time to test again yet. 
I want to redo my install to check why I don't have the static content and see how to disable the scraper for the sites I'm not interested in (so commenting a lot in activePlugins.py I think).
Indeed about the scrape function described in the readme... sorry, my fault, I'm not fluent in english and misunderstood scraping to meaning indexing the content, not downloading everything. My bad. That's why I was surprised and let everything activated the first time... I'll try to restrict the scraper by playing with the activePlugins.py file first, and see otherwise what I can do.

Thank you very much for your support!

**Comment by fake-name** [comment]
No problem. The readme doesn't exactly make the scrape behaviour blatantly apparent.

If you can figure out what's going on with why you're missing the web content, let me know. If it's an oversight in the docs, I can fix it it to the readme.

**Comment by fake-name** [comment]
Closing this due to lack of action.
