### ISSUE TITLE
ImportError: No module named 'utilities.runPlugin'

### ISSUE THREAD

**Issue by jtara1** [fake-name/MangaCMS#13]
I got all the pre-requisites set up running the installer shell file in setuptools.

Using Python 3.5.2

I'm trying to run `python3 mainScrape.py`, but I'm getting an Import error as there really seems to be no file called **./utilities/runPlugin.py**

**Comment by fake-name** [comment]
Well, that's pretty derp-tastic on my part. Apparently I forgot to commit that file to version control. 

I r dum, I guess.
