### ISSUE TITLE
pls fix madokami uploader

### ISSUE THREAD

**Issue by qqueue** [fake-name/MangaCMS#18]
We're all so lonely without it.

**Comment by deusexcalamus** [comment]
pls fake-name, be our fake-name tonight ok?

**Comment by fake-name** [comment]
Lawl, it broke?

I'm so bad about IRC.

**Comment by deusexcalamus** [comment]
Step it up, senpai.

**Comment by fake-name** [comment]
I think this was resolved by restarting the scraper.

Another process had bloated up and consumed all the free memory, so the OOM killer was just killing shit at random.
