### ISSUE TITLE
Does it require internet connection to scrape?

### ISSUE THREAD

**Issue by GodOfConquest** [fake-name/MangaCMS#6]
First of all, Its a great program. I'm great fan of yours (i won't disagree). Its the best scrapper i have ever came across. I respect you.
Please keep it up. I will be in your gratitude. Thanks.
Secondly, I haven't tried it but i would like to know by installing MANGA CMS on my VPS. Will it scrape Manga and Light Novels without internet connection of mine? Will it use Server Bandwidth to download Mangas or my internet cap?

**Comment by fake-name** [comment]
Uh.... What? It shouldn't touch your local Internet connection at all. If it's on a VPS, and that VPS is on the internet, it'll just use the VPS'es connection.
