### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by Vliro** [fake-name/MangaCMS#9]
Had many issues during installation but none that weren't easy to solve, fortunately. However, regardless of what I do I get the error that irc.buffer does not exist, i.e. no module irc.buffer . I've run the setup script and ran pip3 install irc, however it just doesn't run. I attempted to unload the plugins as well however that didn't really work either. 

Edit: by uncommenting the import(not sure if that will work later on) bypassed that part, however now it gives error that relation "ap_scheduler jobs" does not exist for database, it seems to connect properly however I am unsure. I've setup database 9.4.8.

**Comment by fake-name** [comment]
It's been quite a while since I did a clean install of mangacms, and it would not surprise me at all if the installer scripts have drifted out of sync. I'll run one in a VM after work and see what's broken.

**Comment by fake-name** [comment]
After a few patches (the `irc` library removed some stuff, the scheduler ordering 
I got mangacms working with the following process:

#### Note: On Ubuntu 14.04 (not tested anywhere else)

- Add postgresql apt repositories from [here](http://www.postgresql.org/download/linux/ubuntu/)
- From the `setuptools` folder in the project, run `installDeps.sh`
- Set up the DB as described in the README.md file.
- Copy `settings.base.py` to `settings.py`, update file with valid paths.

`python3 runScrape.py` and `python3 runWeb.py` then both seem to work fine.

**Comment by fake-name** [comment]
Any luck?

**Comment by fake-name** [comment]
Closing due to lack of response.
